
package poo.ascensores;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

public class VistaCliente extends javax.swing.JFrame {
    private InterfazRemota ir;
    private int idCliente = 0;
    private int plantaActual = 0;
    private int plantaMin = 0, plantaMax = 0;
    private int ascensorSeleccionado = -1; // Inicialmente ninguno
    
    public VistaCliente() throws RemoteException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        plantaField = new javax.swing.JTextField();
        subirButton = new javax.swing.JButton();
        bajarButton = new javax.swing.JButton();
        plantasSpinner = new javax.swing.JSpinner();
        irButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ascensorField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Ascensor", "Planta", "Ocupado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PLANTA");

        plantaField.setEditable(false);
        plantaField.setText("0");

        subirButton.setText("Subir");
        subirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirButtonActionPerformed(evt);
            }
        });

        bajarButton.setText("Bajar");
        bajarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajarButtonActionPerformed(evt);
            }
        });

        irButton.setText("Ir");
        irButton.setEnabled(false);
        irButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ASCENSOR");

        ascensorField.setEditable(false);
        ascensorField.setToolTipText("id del ascensor asignado");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("ID");

        idField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plantaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ascensorField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bajarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plantasSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(irButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plantaField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(ascensorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(subirButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bajarButton)
                        .addGap(51, 51, 51)
                        .addComponent(plantasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(irButton)))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirButtonActionPerformed
        // TODO add your handling code here:
        solicitarAscensor();
    }//GEN-LAST:event_subirButtonActionPerformed

    private void bajarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajarButtonActionPerformed
        // TODO add your handling code here:
        solicitarAscensor();
    }//GEN-LAST:event_bajarButtonActionPerformed

    private void irButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irButtonActionPerformed
        // TODO add your handling code here:
        int plantaDestino = (int) plantasSpinner.getValue();
        try {
            ir.irAPlanta(ascensorSeleccionado, plantaDestino, idCliente);
            plantaActual = plantaDestino;
            actualizarPlanta(plantaActual);
            
            ir.liberarAscensor(ascensorSeleccionado);
            ascensorField.setText("");
            ascensorSeleccionado = -1;
        } catch (RemoteException ex) {
            Logger.getLogger(VistaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        irButton.setEnabled(false);
        // Se ha llegado a una nueva planta, se puede volver a solicitar un nuevo ascensor
        subirButton.setEnabled(true); 
        bajarButton.setEnabled(true);
    }//GEN-LAST:event_irButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:                                
        try {
            if (ir != null && ascensorSeleccionado >= 0) {
                ir.liberarAscensor(ascensorSeleccionado);
            }
        } catch (Exception e) {
            System.err.println("Error al liberar ascensor en cierre: " + e.getMessage());
        }
        System.exit(0); // Matar el hilo
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VistaCliente().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(VistaCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ascensorField;
    private javax.swing.JButton bajarButton;
    private javax.swing.JTextField idField;
    private javax.swing.JButton irButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField plantaField;
    private javax.swing.JSpinner plantasSpinner;
    private javax.swing.JButton subirButton;
    // End of variables declaration//GEN-END:variables
    
    public void solicitarAscensor()
    {
        System.out.println("Has solicitado un ascensor");
        try {
            ascensorSeleccionado = ir.solicitarAscensor(plantaActual, idCliente);
            System.out.println("Se te ha asignado el ascensor: "+ascensorSeleccionado);
        } catch (RemoteException ex) {
            Logger.getLogger(VistaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        ascensorField.setText(String.valueOf(ascensorSeleccionado));
        irButton.setEnabled(true);
        subirButton.setEnabled(false); // No se pueden solicitar más de 1 ascensor a la vez
        bajarButton.setEnabled(false);
    }
    
    public void actualizarDatos(ArrayList<Ascensor> ascensores)
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               try
                {
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.setRowCount(0); // Limpiar
                    for (Ascensor a : ascensores) {
                        model.addRow(new Object[]{
                            a.getId(),
                            a.getPlantaActual(),
                            a.isOcupado()
                        });
                    }
                } catch(Exception e)
                {
                    System.out.println("Problema de conexión");
                } 
            }
        });
    }
    
    public void actualizarPlanta(int planta)
    { 
        plantaField.setText(String.valueOf(planta));
        int plantaAux = planta;
        
        if (String.valueOf(planta).equals(plantaField.getText()))
        {
            // Si la planta no ha cambiado, el spinner sigue igual
            plantaAux = (int) plantasSpinner.getValue();
        }
        
        if(plantaAux > plantaMax)
        {
            plantaAux = plantaMax;
        } else if (plantaAux < plantaMin)
        {
            plantaAux = plantaMin;
        }
        
        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(plantaAux, plantaMin, plantaMax, 1);
        plantasSpinner.setModel(spinnerModel);
    }

    public InterfazRemota getIr() {
        return ir;
    }

    public void setInterfazRemota(InterfazRemota ir) {
        this.ir = ir;
    }

    public int getIdCliente() {
        return idCliente;
    }

    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
        this.idField.setText(String.valueOf(idCliente));
    }

    public int getPlantaActual() {
        return plantaActual;
    }

    public void setPlantaActual(int plantaActual) {
        this.plantaActual = plantaActual;
    }

    public int getPlantaMin() {
        return plantaMin;
    }

    public void setPlantaMin(int plantaMin) {
        this.plantaMin = plantaMin;
        actualizarPlanta(plantaActual);
    }

    public int getPlantaMax() {
        return plantaMax;
    }

    public void setPlantaMax(int plantaMax) {
        this.plantaMax = plantaMax;
        actualizarPlanta(plantaActual);
    }
    
    
}
